substitutions:
  project_version: "dev"

esphome:
  name: image-display
  friendly_name: Image Display
  name_add_mac_suffix: true
  project:
    name: "Local Display.Image Display"
    version: ${project_version}
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: display_brightness
          brightness: 1.0

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

external_components:
  - source: github://avwuff/ESPHome-HUB75-MatrixDisplayWrapper@4fc1f26500b97a39693cd8af4ba2abb75f83ce0b
  - source:
      type: local
      path: components

logger:
  level: DEBUG

wifi:
  ssid: "HV-NET"
  password: "quicklake713"
  power_save_mode: "NONE"
  ap:
    ssid: "Transit Tracker Fallback"
    password: "quicklake713"

captive_portal:

api:
  reboot_timeout: 0s

http_request:
  verify_ssl: false

ota:
  - platform: http_request
  - platform: esphome
    password: ""

button:
  - platform: restart
    name: "Restart"
  - platform: template
    id: reload_tracker
    on_press:
      - lambda: |-
          id(tracker).reconnect();
  - platform: template
    id: write_preferences
    on_press:
      - lambda: |-
          global_preferences->sync();
  - platform: template
    id: cycle_brightness
    name: "Cycle Brightness"
    on_press:
      - lambda: |-
          // Cycle brightness through discrete levels: 0%, 25%, 50%, 75%, 100%
          static const float levels[] = {0.0, 0.25, 0.5, 0.75, 1.0};
          static const int num_levels = sizeof(levels) / sizeof(levels[0]);

          // Get current brightness (0.0 to 1.0)
          float current_brightness = id(display_brightness).remote_values.get_brightness();

          // Find current level index (with tolerance for floating point)
          int current_index = 0;
          for (int i = 0; i < num_levels; i++) {
            if (fabs(current_brightness - levels[i]) < 0.05) {
              current_index = i;
              break;
            }
          }

          // Move to next level (cycle back to start after 100%)
          int next_index = (current_index + 1) % num_levels;
          float next_brightness = levels[next_index];

          // Set new brightness
          auto call = id(display_brightness).turn_on();
          call.set_brightness(next_brightness);
          call.perform();

text:
  - platform: template
    id: base_url_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |
          id(tracker).set_base_url(id(base_url_config)->state);
  - platform: template
    id: feed_code_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |
          id(tracker).set_feed_code(id(feed_code_config)->state);
  - platform: template
    id: schedule_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |
          id(tracker).set_schedule_string(id(schedule_config)->state);
  - platform: template
    id: abbreviations_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |
          id(tracker).set_abbreviations_from_text(id(abbreviations_config)->state);
  - platform: template
    id: route_styles_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |
          id(tracker).set_route_styles_from_text(id(route_styles_config)->state);

select:
  - platform: template
    id: time_display_config
    optimistic: true
    restore_value: true
    options:
      - "departure"
      - "arrival"
    on_value:
      then:
        lambda: |-
          id(tracker).set_display_departure_times(id(time_display_config)->state == "departure");
  - platform: template
    id: time_units_config
    optimistic: true
    restore_value: true
    options:
      - "long"
      - "short"
      - "none"
    on_value:
      then:
        lambda: |-
          transit_tracker::UnitDisplay unit_display;
          if (id(time_units_config)->state == "long") {
            unit_display = transit_tracker::UnitDisplay::UNIT_DISPLAY_LONG;
          } else if (id(time_units_config)->state == "short") {
            unit_display = transit_tracker::UnitDisplay::UNIT_DISPLAY_SHORT;
          } else {
            unit_display = transit_tracker::UnitDisplay::UNIT_DISPLAY_NONE;
          }

          id(tracker).set_unit_display(unit_display);
  - platform: template
    id: list_mode_config
    optimistic: true
    restore_value: true
    options:
      - "sequential"
      - "nextPerRoute"
    on_value:
      then:
        lambda: |-
          id(tracker).set_list_mode(id(list_mode_config)->state);

number:
  - platform: hub75_matrix_display
    matrix_id: matrix
    id: display_brightness_number

output:
  - platform: template
    id: display_brightness_output
    type: float
    write_action:
      - number.set:
          id: display_brightness_number
          value: !lambda return state * 255.0;

light:
  - platform: monochromatic
    name: Display Brightness
    id: display_brightness
    output: display_brightness_output
    restore_mode: RESTORE_DEFAULT_ON

script:
  - id: dim_display
    parameters:
      up: bool
    then:
      - light.dim_relative:
          id: display_brightness
          relative_brightness: !lambda "return up ? 0.2 : -0.2;"
          transition_length: 0.1s
display:
  - platform: hub75_matrix_display
    id: matrix
    update_interval: 32ms
    width: 64
    height: 32
    chain_length: 2
    R1_pin: 42
    G1_pin: 40
    B1_pin: 41
    R2_pin: 38
    G2_pin: 37
    B2_pin: 39
    A_pin: 45
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2
    clock_phase: false
    i2sspeed: HZ_20M
    brightness: 255
    pages:
      - id: transit_schedule
        lambda: |-
          id(tracker).draw_schedule();
      - id: image_page
        lambda: |-
          // Horizontal continuous scrolling of logos
          esphome::display::BaseImage *logos[] = {
            id(atlanta_united_footballlogos_org_14x14),
            id(austin_fc_footballlogos_org_14x14),
            id(cf_montreal_footballlogos_org_14x14),
            id(charlotte_fc_footballlogos_org_14x14),
            id(chicago_fire_footballlogos_org_14x14),
            id(colorado_rapids_footballlogos_org_14x14),
            id(columbus_crew_footballlogos_org_14x14),
            id(dc_united_footballlogos_org_14x14),
            id(fc_cincinnati_footballlogos_org_14x14),
            id(fc_dallas_footballlogos_org_14x14),
            id(houston_dynamo_footballlogos_org_14x14),
            id(inter_miami_footballlogos_org_14x14),
            id(los_angeles_fc_footballlogos_org_14x14),
            id(los_angeles_galaxy_footballlogos_org_14x14),
            id(minnesota_united_footballlogos_org_14x14),
            id(mls_footballlogos_org_14x14),
            id(nashville_sc_footballlogos_org_14x14),
            id(new_england_revolution_footballlogos_org_14x14),
            id(new_york_city_fc_footballlogos_org_14x14),
            id(new_york_red_bulls_footballlogos_org_14x14),
            id(orlando_city_footballlogos_org_14x14),
            id(philadelphia_union_footballlogos_org_14x14),
            id(portland_timbers_footballlogos_org_14x14),
            id(real_salt_lake_footballlogos_org_14x14),
            id(san_diego_fc_footballlogos_org_14x14),
            id(san_jose_earthquakes_footballlogos_org_14x14),
            id(seattle_sounders_footballlogos_org_14x14),
            id(sporting_kansas_city_footballlogos_org_14x14),
            id(st_louis_city_footballlogos_org_14x14),
            id(toronto_fc_footballlogos_org_14x14),
            id(vancouver_whitecaps_footballlogos_org_14x14)
          };

          const int total = sizeof(logos)/sizeof(logos[0]);
          if (total == 0) return;

          // Assume uniform logo size
          const int logo_w = logos[0]->get_width();
          const int logo_h = logos[0]->get_height();
          const int gap = 2; // pixels between logos

          // Scroll speed in pixels per second
          const int speed_px_per_sec = 6;
          const unsigned long now_ms = millis();

          const int stride = logo_w + gap; // spacing per logo
          const int strip_len = total * stride;

          // Continuous left scroll offset
          int offset = (now_ms * speed_px_per_sec / 1000) % strip_len;

          // Y position centered vertically
          int y = (it.get_height() - logo_h) / 2;

          // Draw all logos in scrolling loop
          for (int logo_idx = 0; logo_idx < total; logo_idx++) {
            int strip_x = (logo_idx * stride) - offset;  // position along the virtual strip
            
            // Wrap around for continuous scrolling
            while (strip_x < -logo_w) strip_x += strip_len;
            while (strip_x >= it.get_width()) strip_x -= strip_len;

            // Only draw if within visible area (with small padding)
            if (strip_x < it.get_width() && strip_x > -logo_w) {
              it.image(strip_x, y, logos[logo_idx]);
            }
          }

      - id: ip_address_page
        lambda: |-
          int x = it.get_width() / 2;
          int y = it.get_height() / 2;

          auto ip_addresses = ::esphome::network::get_ip_addresses();
          if (ip_addresses.empty()) {
            it.printf(x, y, id(pixolletta), COLOR_ON, TextAlign::CENTER, "No IP Address");
            return;
          }
          it.printf(x, y, id(pixolletta), COLOR_ON, TextAlign::CENTER, "%s", ip_addresses[0].str().c_str());

font:
  - file: "fonts/Pixolletta8px.ttf"
    id: pixolletta
    size: 10
    glyphs:
      - abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:;!?()"'-+/*=%@#[]{}<>|&^~
      - ÄËÏÖÜÉÈÔäëïöüéèôŊŋÁÊÎÛÝáêîûýĜĝÀÌÒàìòÑñÍÓÚíóúÇçĆČĐŠŽćčđšžÙùÕõŞŁŇŘşłňřÅåØøĀĒĪŌŪāēīōūÂâĞğıĎĚŤŮďěťůÆæĲĳŒœÐðŸÿßŐŰőűÞþÃãĂĔĬŎŬăĕĭŏŭĨŨĩũĄĘŃŚŻąęńśżĖėĢĶĻŅģķļņĮŲįųŔŹŕźĊĠċġħŜŝŢţŦŧŴŵŶŷĹĽĺľİ
      - " "

binary_sensor:
  - platform: gpio
    pin:
      number: 6 # BUTTON_UP
      mode: INPUT_PULLUP
      inverted: true
    name: "Up Button"
    on_press:
      - lambda: |-
          // Swap to previous page
          id(matrix).show_prev_page();

  - platform: gpio
    pin:
      number: 7 # BUTTON_DOWN
      mode: INPUT_PULLUP
      inverted: true
    name: "Down Button"
    on_press:
      - lambda: |-
          // Reversible dimmer: 5 steps from full to off, then back up
          static int direction = -1;  // -1 = dimming, +1 = brightening
          const float step = 0.2f;    // five clicks from 1.0 to 0.0

          float current = id(display_brightness).remote_values.get_brightness();
          if (current < 0.0f) current = 0.0f;
          if (current > 1.0f) current = 1.0f;

          float next = current + step * direction;
          if (next < 0.0f) next = 0.0f;
          if (next > 1.0f) next = 1.0f;

          auto call = id(display_brightness).turn_on();
          call.set_brightness(next);
          call.perform();

          // Reverse direction when an endpoint is reached
          if (next <= 0.001f) {
            direction = +1;
          } else if (next >= 0.999f) {
            direction = -1;
          }

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

web_server:

color:
  - id: rapidride_red
    hex: "F50046"
  - id: "c_FDB71A"
    hex: "FDB71A"

transit_tracker:
  id: "tracker"
  base_url: "wss://tt.horner.tj/"
  time_display: "arrival"
  show_units: "long"
  list_mode: "sequential"
  stops:
    - stop_id: "st:1_24440"
      time_offset: "-1min"
      routes:
        - "st:1_100132"
  styles:
    - route_id: "st:1_100132"
      name: "24"
      color: "c_FDB71A"
  abbreviations:
    - from: "Downtown"
      to: "DwnTn"
image:
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\atlanta-united-footballlogos-org_14x14.png"
    id: atlanta_united_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\austin-fc-footballlogos-org_14x14.png"
    id: austin_fc_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\cf-montreal-footballlogos-org_14x14.png"
    id: cf_montreal_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\charlotte-fc-footballlogos-org_14x14.png"
    id: charlotte_fc_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\chicago-fire-footballlogos-org_14x14.png"
    id: chicago_fire_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\colorado-rapids-footballlogos-org_14x14.png"
    id: colorado_rapids_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\columbus-crew-footballlogos-org_14x14.png"
    id: columbus_crew_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\dc-united-footballlogos-org_14x14.png"
    id: dc_united_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\fc-cincinnati-footballlogos-org_14x14.png"
    id: fc_cincinnati_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\fc-dallas-footballlogos-org_14x14.png"
    id: fc_dallas_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\houston-dynamo-footballlogos-org_14x14.png"
    id: houston_dynamo_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\inter-miami-footballlogos-org_14x14.png"
    id: inter_miami_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\los-angeles-fc-footballlogos-org_14x14.png"
    id: los_angeles_fc_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\los-angeles-galaxy-footballlogos-org_14x14.png"
    id: los_angeles_galaxy_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\minnesota-united-footballlogos-org_14x14.png"
    id: minnesota_united_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\mls-footballlogos-org_14x14.png"
    id: mls_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\nashville-sc-footballlogos-org_14x14.png"
    id: nashville_sc_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\new-england-revolution-footballlogos-org_14x14.png"
    id: new_england_revolution_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\new-york-city-fc-footballlogos-org_14x14.png"
    id: new_york_city_fc_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\new-york-red-bulls-footballlogos-org_14x14.png"
    id: new_york_red_bulls_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\orlando-city-footballlogos-org_14x14.png"
    id: orlando_city_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\philadelphia-union-footballlogos-org_14x14.png"
    id: philadelphia_union_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\portland-timbers-footballlogos-org_14x14.png"
    id: portland_timbers_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\real-salt-lake-footballlogos-org_14x14.png"
    id: real_salt_lake_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\san-diego-fc-footballlogos-org_14x14.png"
    id: san_diego_fc_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\san-jose-earthquakes-footballlogos-org_14x14.png"
    id: san_jose_earthquakes_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\seattle-sounders-footballlogos-org_14x14.png"
    id: seattle_sounders_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\sporting-kansas-city-footballlogos-org_14x14.png"
    id: sporting_kansas_city_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\st-louis-city-footballlogos-org_14x14.png"
    id: st_louis_city_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\toronto-fc-footballlogos-org_14x14.png"
    id: toronto_fc_footballlogos_org_14x14
    type: RGB565
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\vancouver-whitecaps-footballlogos-org_14x14.png"
    id: vancouver_whitecaps_footballlogos_org_14x14
    type: RGB565
