substitutions:
  project_version: "dev"

esphome:
  name: soccer-tracker
  friendly_name: Soccer Tracker
  name_add_mac_suffix: true
  project:
    name: "Soccer Display.Soccer Tracker"
    version: ${project_version}
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: display_brightness
          brightness: 1.0
  platformio_options:
    build_flags: -DSOCCER_TEST_MODE=1
      -DSOCCER_TEST_SERVER_URL=\"http://192.168.11.127:5000\"

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

external_components:
  - source: github://avwuff/ESPHome-HUB75-MatrixDisplayWrapper@4fc1f26500b97a39693cd8af4ba2abb75f83ce0b
  - source:
      type: local
      path: components

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: "NONE"
  ap:
    ssid: "Soccer Tracker Fallback"
    password: !secret wifi_password

captive_portal:

api:
  reboot_timeout: 0s

http_request:
  id: http_request_component
  verify_ssl: false
  timeout: 10s

ota:
  - platform: http_request
  - platform: esphome
    password: ""

button:
  - platform: restart
    name: "Restart"
  - platform: template
    id: cycle_brightness
    name: "Cycle Brightness"
    on_press:
      - lambda: |-
          static const float levels[] = {0.0, 0.25, 0.5, 0.75, 1.0};
          static const int num_levels = sizeof(levels) / sizeof(levels[0]);

          float current_brightness = id(display_brightness).remote_values.get_brightness();

          int current_index = 0;
          for (int i = 0; i < num_levels; i++) {
            if (fabs(current_brightness - levels[i]) < 0.05) {
              current_index = i;
              break;
            }
          }

          int next_index = (current_index + 1) % num_levels;
          float next_brightness = levels[next_index];

          auto call = id(display_brightness).turn_on();
          call.set_brightness(next_brightness);
          call.perform();

number:
  - platform: hub75_matrix_display
    matrix_id: matrix
    id: display_brightness_number

output:
  - platform: template
    id: display_brightness_output
    type: float
    write_action:
      - number.set:
          id: display_brightness_number
          value: !lambda return state * 255.0;

light:
  - platform: monochromatic
    name: Display Brightness
    id: display_brightness
    output: display_brightness_output
    restore_mode: RESTORE_DEFAULT_ON

font:
  - file: "fonts/Pixolletta8px.ttf"
    id: pixolletta
    size: 8
    glyphs:
      - ' !"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'

  - file: "fonts/Pixolletta8px.ttf"
    id: pixolletta_small
    size: 6
    glyphs:
      - ' !"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'

binary_sensor:
  - platform: gpio
    pin:
      number: 6 # BUTTON_UP
      mode: INPUT_PULLUP
      inverted: true
    name: "Up Button"
    on_press:
      - lambda: |-
          id(matrix).show_prev_page();

  - platform: gpio
    pin:
      number: 7 # BUTTON_DOWN
      mode: INPUT_PULLUP
      inverted: true
    name: "Down Button"
    on_press:
      - lambda: |-
          static int direction = -1;
          const float step = 0.2f;

          float current = id(display_brightness).remote_values.get_brightness();
          if (current < 0.0f) current = 0.0f;
          if (current > 1.0f) current = 1.0f;

          float next = current + step * direction;
          if (next < 0.0f) next = 0.0f;
          if (next > 1.0f) next = 1.0f;

          auto call = id(display_brightness).turn_on();
          call.set_brightness(next);
          call.perform();

          if (next <= 0.001f) {
            direction = +1;
          } else if (next >= 0.999f) {
            direction = -1;
          }

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

web_server:

# Import all team logos
image:
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\atlanta-united-footballlogos-org_14x14.png"
    id: atlanta_united_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\austin-fc-footballlogos-org_14x14.png"
    id: austin_fc_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\cf-montreal-footballlogos-org_14x14.png"
    id: cf_montreal_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\charlotte-fc-footballlogos-org_14x14.png"
    id: charlotte_fc_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\chicago-fire-footballlogos-org_14x14.png"
    id: chicago_fire_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\colorado-rapids-footballlogos-org_14x14.png"
    id: colorado_rapids_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\columbus-crew-footballlogos-org_14x14.png"
    id: columbus_crew_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\dc-united-footballlogos-org_14x14.png"
    id: dc_united_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\fc-cincinnati-footballlogos-org_14x14.png"
    id: fc_cincinnati_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\fc-dallas-footballlogos-org_14x14.png"
    id: fc_dallas_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\houston-dynamo-footballlogos-org_14x14.png"
    id: houston_dynamo_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\inter-miami-footballlogos-org_14x14.png"
    id: inter_miami_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\los-angeles-fc-footballlogos-org_14x14.png"
    id: los_angeles_fc_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\los-angeles-galaxy-footballlogos-org_14x14.png"
    id: los_angeles_galaxy_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\minnesota-united-footballlogos-org_14x14.png"
    id: minnesota_united_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\nashville-sc-footballlogos-org_14x14.png"
    id: nashville_sc_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\new-england-revolution-footballlogos-org_14x14.png"
    id: new_england_revolution_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\new-york-city-fc-footballlogos-org_14x14.png"
    id: new_york_city_fc_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\new-york-red-bulls-footballlogos-org_14x14.png"
    id: new_york_red_bulls_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\orlando-city-footballlogos-org_14x14.png"
    id: orlando_city_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\philadelphia-union-footballlogos-org_14x14.png"
    id: philadelphia_union_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\portland-timbers-footballlogos-org_14x14.png"
    id: portland_timbers_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\real-salt-lake-footballlogos-org_14x14.png"
    id: real_salt_lake_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\san-diego-fc-footballlogos-org_14x14.png"
    id: san_diego_fc_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\san-jose-earthquakes-footballlogos-org_14x14.png"
    id: san_jose_earthquakes_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\seattle-sounders-footballlogos-org_14x14.png"
    id: seattle_sounders_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\sporting-kansas-city-footballlogos-org_14x14.png"
    id: sporting_kansas_city_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\st-louis-city-footballlogos-org_14x14.png"
    id: st_louis_city_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\toronto-fc-footballlogos-org_14x14.png"
    id: toronto_fc_logo
    type: RGB
    transparency: alpha_channel
  - file: "C:\\Users\\bcrow\\transit-tracker\\firmware\\logos\\teams_resized\\vancouver-whitecaps-footballlogos-org_14x14.png"
    id: vancouver_whitecaps_logo
    type: RGB
    transparency: alpha_channel

# Soccer tracker configuration
soccer_tracker:
  id: "soccer"
  display_id: matrix
  font_id: pixolletta
  small_font_id: pixolletta_small
  time_id: sntp_time
  http_request_id: http_request_component
  api_key: !secret api_football_api_key # From https://www.api-football.com/
  favorite_team: "Seattle Sounders FC" # Change to your favorite MLS team
  team_id: 1595 # Seattle Sounders FC team ID from API-Football (MLS is fully supported)
  team_logos:
    "atlanta-united-footballlogos-org_14x14.png": atlanta_united_logo
    "austin-fc-footballlogos-org_14x14.png": austin_fc_logo
    "cf-montreal-footballlogos-org_14x14.png": cf_montreal_logo
    "charlotte-fc-footballlogos-org_14x14.png": charlotte_fc_logo
    "chicago-fire-footballlogos-org_14x14.png": chicago_fire_logo
    "colorado-rapids-footballlogos-org_14x14.png": colorado_rapids_logo
    "columbus-crew-footballlogos-org_14x14.png": columbus_crew_logo
    "dc-united-footballlogos-org_14x14.png": dc_united_logo
    "fc-cincinnati-footballlogos-org_14x14.png": fc_cincinnati_logo
    "fc-dallas-footballlogos-org_14x14.png": fc_dallas_logo
    "houston-dynamo-footballlogos-org_14x14.png": houston_dynamo_logo
    "inter-miami-footballlogos-org_14x14.png": inter_miami_logo
    "los-angeles-fc-footballlogos-org_14x14.png": los_angeles_fc_logo
    "los-angeles-galaxy-footballlogos-org_14x14.png": los_angeles_galaxy_logo
    "minnesota-united-footballlogos-org_14x14.png": minnesota_united_logo
    "nashville-sc-footballlogos-org_14x14.png": nashville_sc_logo
    "new-england-revolution-footballlogos-org_14x14.png": new_england_revolution_logo
    "new-york-city-fc-footballlogos-org_14x14.png": new_york_city_fc_logo
    "new-york-red-bulls-footballlogos-org_14x14.png": new_york_red_bulls_logo
    "orlando-city-footballlogos-org_14x14.png": orlando_city_logo
    "philadelphia-union-footballlogos-org_14x14.png": philadelphia_union_logo
    "portland-timbers-footballlogos-org_14x14.png": portland_timbers_logo
    "real-salt-lake-footballlogos-org_14x14.png": real_salt_lake_logo
    "san-diego-fc-footballlogos-org_14x14.png": san_diego_fc_logo
    "san-jose-earthquakes-footballlogos-org_14x14.png": san_jose_earthquakes_logo
    "seattle-sounders-footballlogos-org_14x14.png": seattle_sounders_logo
    "sporting-kansas-city-footballlogos-org_14x14.png": sporting_kansas_city_logo
    "st-louis-city-footballlogos-org_14x14.png": st_louis_city_logo
    "toronto-fc-footballlogos-org_14x14.png": toronto_fc_logo
    "vancouver-whitecaps-footballlogos-org_14x14.png": vancouver_whitecaps_logo

display:
  - platform: hub75_matrix_display
    id: matrix
    update_interval: 32ms
    width: 64
    height: 32
    chain_length: 2
    R1_pin: 42
    G1_pin: 40
    B1_pin: 41
    R2_pin: 38
    G2_pin: 37
    B2_pin: 39
    A_pin: 45
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2
    clock_phase: false
    i2sspeed: HZ_20M
    brightness: 255
    pages:
      - id: soccer_page
        lambda: |-
          id(soccer).draw_match();
      - id: ip_address_page
        lambda: |-
          int x = it.get_width() / 2;
          int y = it.get_height() / 2;

          auto ip_addresses = ::esphome::network::get_ip_addresses();
          if (ip_addresses.empty()) {
            it.printf(x, y, id(pixolletta), COLOR_ON, TextAlign::CENTER, "No IP Address");
          } else {
            it.printf(x, y, id(pixolletta), COLOR_ON, TextAlign::CENTER, "%s", ip_addresses[0].str().c_str());
          }
